name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Ubuntu_Latest_GCC",
            os: ubuntu-latest,
            build_type: "Debug",
            targetFolder: "./",
            exeExtension: "",
            cc: "gcc-9",
            cxx: "g++-9"
          }
        - {
            name: "Windows Latest MSVC",
            os: windows-latest,
            build_type: "Debug",
            targetFolder: "Debug/", # Must match build_type.
            exeExtension: ".exe",
            cc: "cl",
            cxx: "cl",
            generators: "Visual Studio 16 2019"
          }

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies on ubuntu
      if: startsWith(matrix.config.name, 'Ubuntu_Latest_GCC')
      run: |
        sudo apt-get update
        sudo apt-get install cmake ${{ matrix.config.cc }} ${{ matrix.config.cxx }} qt5-default libasound2-dev
        cmake --version
        gcc --version
        g++ --version
        qtchooser -print-env

    - name: Install CMake on Windows
      if: startsWith(matrix.config.os, 'windows')
      run: |
        choco install cmake

    - name: Install Qt on Windows
      if: startsWith(matrix.config.os, 'windows')
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        setup-python: 'false'

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
      env:
        CC:   ${{ matrix.config.cc }}
        CXX:  ${{ matrix.config.cxx }}

    - name: Build
      run: cmake --build build --config ${{ matrix.config.build_type }}

    - name: CommonTest
      working-directory: build
      shell: bash
      run: BabelWires/Tests/Common/${{ matrix.config.targetFolder }}commonTests${{ matrix.config.exeExtension }}

    - name: BabelWiresTest
      working-directory: build
      shell: bash
      run: BabelWires/Tests/BabelWires/${{ matrix.config.targetFolder }}babelWiresTests${{ matrix.config.exeExtension }}

    - name: SequenceLibTests
      working-directory: build
      shell: bash
      run: Tests/SeqWiresLib/${{ matrix.config.targetFolder }}sequenceLibTests${{ matrix.config.exeExtension }}

    - name: Seq2tapeLibTests
      working-directory: build
      shell: bash
      run: Tests/Seq2tapeLib/${{ matrix.config.targetFolder }}seq2tapeLibTests${{ matrix.config.exeExtension }}

    - name: AlsaTests
      if: startsWith(matrix.config.name, 'Ubuntu')
      working-directory: build
      shell: bash
      run: BabelWiresAudio/Alsa/Tests/${{ matrix.config.targetFolder }}alsaTests${{ matrix.config.exeExtension }}

    - name: SmfTests
      working-directory: build/BabelWiresPlugins/Smf/Tests
      shell: bash
      run: {{ matrix.config.targetFolder }}SmfTests${{ matrix.config.exeExtension }}
